#! /usr/bin/env python3
# vim:fenc=utf-8
#
# Copyright © 2024 zzq <zzq@zzq-HP-Pavilion-Gaming-Laptop-15-cx0xxx>
#
# Distributed under terms of the MIT license.

import sys
import os
script_name = sys.argv[0]

script_arg_num = len(sys.argv)
script_arg_require_arg_num = 1

parameter_name_list = [1 ,2 ,3]

if script_arg_num <= script_arg_require_arg_num :
    print(f"传入参数数目{script_arg_num} <= 最低参数个数{script_arg_require_arg_num}")
    exit( -1)

commonds = sys.argv[1:]

commond_str = " ".join(commonds)
print(commond_str)

os.system (commond_str)


