#!/bin/bash
# this is script product script(这是一个生成脚本的脚本)
# input xxx.sh and script_name that it's name must be "zzq" at first(输入.sh文件，和脚本名字，脚本名必须是zzq开头)
# 使用：zzqscript xxx.sh 即得到一个名称为zzqxxx的脚本

parameter_names=(1 运行模式 待压缩文件的绝对路径  保存压缩文件的目录 4 5 6)

password=888888
script_dir_path=$(pwd)
#输入参数的名称列表
parameter_num=1  # 脚本一定需要传入的参数个数
shell_script_path=$PART_EXE_SCRIPT_PATH   # 脚本待调用的脚本的父目录
son_script_path=makefiles  # 待调用的脚本的子目录
call_script_path="$shell_script_path""$son_script_path"


#检测参数是否正确传入
for i in $(seq 1 $parameter_num)
do
    if [ -z ${!i}  ];then # $i是空则输出
        echo "${parameter_names[$i]}:未输入，终止脚本执行"
        exit 1
    else
        echo "${parameter_names[$i]}:${!i}"
    fi
done


script_name=$1
script_path=$script_dir_path"/"$script_name
script_name_no_suffix=${script_name%.*} #获取不带后缀的名字
zzq_save_exe_script_path="/usr/local/bin"
exited_script_name=$(ls $zzq_save_exe_script_path ) #获取已经存在的脚本名字
exe_script_path="$zzq_save_exe_script_path""/$script_name_no_suffix"
# 将新取的名字和已经存在的脚本名进行对比，相同则报错

#新脚本名合法则生成脚本
sudo cp  $script_path $exe_script_path
echo "赋予脚本权限"
sudo chown root: $exe_script_path
sudo chmod 755 $exe_script_path
echo "脚本移植完成"
